### PR TITLE
Bug memory kws

### PR DESCRIPTION
**Pull request by owlas**
Just tried out this package, looks like a great implementation.

I ran this on a large dataset (much bigger than memory) and ran into the following problem that the keywords were not being passed along. Was there a reason for this?

If not, small fix is in this PR.

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for doing this. This was a bug! 

I think that the Travis error on the test is just an unrelated glitch, so I am rerunning that build.

**Comment by owlas** [comment]
Great, let me know if there is anything else you need.

**Comment by arokem** [comment]
Could you remove `duecredit` from the requirements? I don't think that it needs to be a strict requirement.

**Comment by owlas** [comment]
I don't think I was able to import without the requirement. Are you able to? It's imported in the main module

**Comment by arokem** [comment]
It's a bit confusing. The `due` module is imported locally in the main module, but inside that module, `duecredit` is an optional import under a `try` clause: 

https://github.com/scikit-learn-contrib/forest-confidence-interval/blob/master/forestci/due.py#L48

I believe that you should be able to import our package without duecredit.

**Comment by owlas** [comment]
@arokem sorry for leaving this for so long. I've removed the change to the requirements file.

**Comment by arokem** [comment]
Fantastic. Thanks for doing this!

**Pull request merged**
