### PR TITLE
MRG: Calibration with empirical Bayes.

### PR DESCRIPTION
**Pull request by arokem**
This is the work of hzhao16 from #48, but without some large data files
that got added into the history along the way. Also, several added PEP8
fixes, and more comprehensive testing.

This extends and supersedes #48

### CODE REVIEW

**Comment by hzhao16** [comment]
@arokem Btw, I changed the default parameter of gfit. The original nbins=200 does not work on my dataset, possibly because it is a large dataset and bin width would be wide. I changed it to 100000, however this will make the calculation slower.

**Comment by arokem** [comment]
I have not managed to fix the history for this branch, and I just don't have time to fixe this, so we will end up with duplications of some commits.

**Comment by arokem** [comment]
IMPORTANT: I suggest that we do not merge this yet. Let's finish all the changes for the JOSS paper first, then make a release, and only then merge this into master. Even if it does pass all the tests, I think that we need to try this out on a few different data-sets, before we put this in a release version.

**Comment by kpolimis** [comment]
ok, will focus on JOSS review and leave this PR alone

**Comment by arokem** [comment]
Rebased on master

**Comment by arokem** [comment]
Rebased again on current master

**Pull request merged**
